

export interface LoginResponseI {
  messages:     string;
  access_token: string;
}

// Generated by https://quicktype.io

export interface UserProfileI {
  msg:  string;
  user: UserI;
}

export interface UserI {
  id:       number;
  nombre:   string;
  apellido: string;
  telefono: string;
  email:    string;
  rol:      string;
}
