

// Generated by https://quicktype.io

export interface ImagenCreateResponseI {
  messages: string;
  imagen:   Imagen;
}

export interface Imagen {
  imagen_url: string;
  id_imagen:  string;
  id:         number;
}
