// Generated by https://quicktype.io
export interface PostCreateI{
  titulo:string,
  descripcion:string,
  lugar:string,
  ciudad:string,
  fecha:any,
  imagen_id:number,
  categoria_id:number
}


export interface PostAllPaginateI {
  Posts: Posts;
}

export interface Posts {
  current_page:   number;
  data:           Datum[];
  first_page_url: string;
  from:           number;
  last_page:      number;
  last_page_url:  string;
  links:          Link[];
  next_page_url:  string;
  path:           string;
  per_page:       number;
  prev_page_url:  null;
  to:             number;
  total:          number;
}

export interface Datum {
  id:                number;
  titulo:            string;
  descripcion:       string;
  lugar:             string;
  ciudad:            string;
  fecha:             string;
  calificacionFinal: number;
  imagen_id:         number;
  categoria_id:      number;
  participante_id:   number;
  participante:      Participante;
  categoria:         Categoria;
  imagen:            Imagen;
  like:              Like[];
  calificacion:      Calificacion[];
  comentario__post:  ComentarioPost[];
}

export interface Calificacion {
  id:                    number;
  total:                 number;
  contenido:             number;
  organizacion_estatica: number;
  creatividad:           number;
  tecnica:               number;
  post_id:               number;
  user_id:               number;
}

export interface Categoria {
  id:     number;
  nombre: string;
}

export interface ComentarioPost {
  id:              number;
  fecha:           string;
  comentario_id:   number;
  participante_id: number;
  post_id:         number;
  comentario:      Comentario;
  participante:    Participante;
}

export interface Comentario {
  id:      number;
  mensaje: string;
}

export interface Participante {
  id:       number;
  nombres:  string;
  cedula:   string;
  email:    string;
  semestre: string;
  telefono: string;
  rol:      string;
}


export interface Imagen {
  id:         number;
  imagen_url: string;
  id_imagen:  string;
}

export interface Like {
  id:              number;
  post_id:         number;
  participante_id: number;
  participante:    Participante;
}

export interface Link {
  url:    null | string;
  label:  string;
  active: boolean;
}
