// Generated by https://quicktype.io

import { Datum } from "./post.interface";


export interface PostSearchByCategoryWithoutCalificationI {
  Post: Post;
}

export interface Post {
  current_page:   number;
  data:           Datum[]|Datum;
  first_page_url: string;
  from:           null;
  last_page:      number;
  last_page_url:  string;
  links:          Link[];
  next_page_url:  null;
  path:           string;
  per_page:       number;
  prev_page_url:  null;
  to:             null;
  total:          number;
}

export interface Link {
  url:    null | string;
  label:  string;
  active: boolean;
}
